version: 1
disable_existing_loggers: false
formatters:
  system:
    format: "%(asctime)s: %(name)s: %(levelname)s: %(message)s"
  gui:
    format: "%(asctime)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: system
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: system
    level: INFO
    filename: .logs/app.log
    when: W6
    interval: 1
    backupCount: 12
    utc: False
    encoding: utf-8
  gui:
    class: libs.gui.logging_textbox.GuiHandler
    formatter: gui
    level: INFO
loggers:
  system:
    level: DEBUG
    handlers:
      - console
    progate: true
  gui:
    level: INFO
    handlers:
      - console
      - file
      - gui
    progate: true
